services:
  php:
    image: php:8.1-fpm
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php